// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.ecommerce.grpc.common;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.common.Empty)
    com.google.protobuf.MessageOrBuilder {
}
