// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

public interface CategoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.product.CategoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string category_id = 1;</code>
   * @return The categoryId.
   */
  java.lang.String getCategoryId();
  /**
   * <code>string category_id = 1;</code>
   * @return The bytes for categoryId.
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string category_name = 2;</code>
   * @return The categoryName.
   */
  java.lang.String getCategoryName();
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string category_name = 2;</code>
   * @return The bytes for categoryName.
   */
  com.google.protobuf.ByteString
      getCategoryNameBytes();

  /**
   * <code>.ecommerce.common.Metadata metadata = 3;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.ecommerce.common.Metadata metadata = 3;</code>
   * @return The metadata.
   */
  com.ecommerce.grpc.common.Metadata getMetadata();
  /**
   * <code>.ecommerce.common.Metadata metadata = 3;</code>
   */
  com.ecommerce.grpc.common.MetadataOrBuilder getMetadataOrBuilder();
}
