// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

public interface CategoryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.product.CategoryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string parent_id = 4;</code>
   * @return The parentId.
   */
  java.lang.String getParentId();
  /**
   * <code>string parent_id = 4;</code>
   * @return The bytes for parentId.
   */
  com.google.protobuf.ByteString
      getParentIdBytes();

  /**
   * <code>int32 level = 5;</code>
   * @return The level.
   */
  int getLevel();
}
