// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.product.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
   * @return Whether the uiAction field is set.
   */
  boolean hasUiAction();
  /**
   * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
   * @return The uiAction.
   */
  com.ecommerce.grpc.product.ProductUIAction getUiAction();
  /**
   * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
   */
  com.ecommerce.grpc.product.ProductUIActionOrBuilder getUiActionOrBuilder();

  /**
   * <code>.ecommerce.common.Status status = 3;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.ecommerce.common.Status status = 3;</code>
   * @return The status.
   */
  com.ecommerce.grpc.common.Status getStatus();
  /**
   * <code>.ecommerce.common.Status status = 3;</code>
   */
  com.ecommerce.grpc.common.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>double latency_ms = 4;</code>
   * @return The latencyMs.
   */
  double getLatencyMs();

  /**
   * <code>.ecommerce.common.Metadata metadata = 5;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.ecommerce.common.Metadata metadata = 5;</code>
   * @return The metadata.
   */
  com.ecommerce.grpc.common.Metadata getMetadata();
  /**
   * <code>.ecommerce.common.Metadata metadata = 5;</code>
   */
  com.ecommerce.grpc.common.MetadataOrBuilder getMetadataOrBuilder();
}
