// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

/**
 * Protobuf type {@code ecommerce.product.ProductResponseChunk}
 */
public final class ProductResponseChunk extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ecommerce.product.ProductResponseChunk)
    ProductResponseChunkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductResponseChunk.newBuilder() to construct.
  private ProductResponseChunk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductResponseChunk() {
    chunk_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductResponseChunk();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductResponseChunk(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            chunk_ = s;
            break;
          }
          case 18: {
            com.ecommerce.grpc.product.ProductUIAction.Builder subBuilder = null;
            if (uiAction_ != null) {
              subBuilder = uiAction_.toBuilder();
            }
            uiAction_ = input.readMessage(com.ecommerce.grpc.product.ProductUIAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(uiAction_);
              uiAction_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            finished_ = input.readBool();
            break;
          }
          case 34: {
            com.ecommerce.grpc.common.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.ecommerce.grpc.common.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductResponseChunk_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductResponseChunk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecommerce.grpc.product.ProductResponseChunk.class, com.ecommerce.grpc.product.ProductResponseChunk.Builder.class);
  }

  public static final int CHUNK_FIELD_NUMBER = 1;
  private volatile java.lang.Object chunk_;
  /**
   * <code>string chunk = 1;</code>
   * @return The chunk.
   */
  @java.lang.Override
  public java.lang.String getChunk() {
    java.lang.Object ref = chunk_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chunk_ = s;
      return s;
    }
  }
  /**
   * <code>string chunk = 1;</code>
   * @return The bytes for chunk.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChunkBytes() {
    java.lang.Object ref = chunk_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chunk_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UI_ACTION_FIELD_NUMBER = 2;
  private com.ecommerce.grpc.product.ProductUIAction uiAction_;
  /**
   * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
   * @return Whether the uiAction field is set.
   */
  @java.lang.Override
  public boolean hasUiAction() {
    return uiAction_ != null;
  }
  /**
   * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
   * @return The uiAction.
   */
  @java.lang.Override
  public com.ecommerce.grpc.product.ProductUIAction getUiAction() {
    return uiAction_ == null ? com.ecommerce.grpc.product.ProductUIAction.getDefaultInstance() : uiAction_;
  }
  /**
   * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.product.ProductUIActionOrBuilder getUiActionOrBuilder() {
    return getUiAction();
  }

  public static final int FINISHED_FIELD_NUMBER = 3;
  private boolean finished_;
  /**
   * <code>bool finished = 3;</code>
   * @return The finished.
   */
  @java.lang.Override
  public boolean getFinished() {
    return finished_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private com.ecommerce.grpc.common.Status status_;
  /**
   * <code>.ecommerce.common.Status status = 4;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.ecommerce.common.Status status = 4;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.Status getStatus() {
    return status_ == null ? com.ecommerce.grpc.common.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.ecommerce.common.Status status = 4;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chunk_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chunk_);
    }
    if (uiAction_ != null) {
      output.writeMessage(2, getUiAction());
    }
    if (finished_ != false) {
      output.writeBool(3, finished_);
    }
    if (status_ != null) {
      output.writeMessage(4, getStatus());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chunk_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chunk_);
    }
    if (uiAction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUiAction());
    }
    if (finished_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, finished_);
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getStatus());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecommerce.grpc.product.ProductResponseChunk)) {
      return super.equals(obj);
    }
    com.ecommerce.grpc.product.ProductResponseChunk other = (com.ecommerce.grpc.product.ProductResponseChunk) obj;

    if (!getChunk()
        .equals(other.getChunk())) return false;
    if (hasUiAction() != other.hasUiAction()) return false;
    if (hasUiAction()) {
      if (!getUiAction()
          .equals(other.getUiAction())) return false;
    }
    if (getFinished()
        != other.getFinished()) return false;
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHUNK_FIELD_NUMBER;
    hash = (53 * hash) + getChunk().hashCode();
    if (hasUiAction()) {
      hash = (37 * hash) + UI_ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getUiAction().hashCode();
    }
    hash = (37 * hash) + FINISHED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFinished());
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.product.ProductResponseChunk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecommerce.grpc.product.ProductResponseChunk prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecommerce.product.ProductResponseChunk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecommerce.product.ProductResponseChunk)
      com.ecommerce.grpc.product.ProductResponseChunkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductResponseChunk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductResponseChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecommerce.grpc.product.ProductResponseChunk.class, com.ecommerce.grpc.product.ProductResponseChunk.Builder.class);
    }

    // Construct using com.ecommerce.grpc.product.ProductResponseChunk.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      chunk_ = "";

      if (uiActionBuilder_ == null) {
        uiAction_ = null;
      } else {
        uiAction_ = null;
        uiActionBuilder_ = null;
      }
      finished_ = false;

      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductResponseChunk_descriptor;
    }

    @java.lang.Override
    public com.ecommerce.grpc.product.ProductResponseChunk getDefaultInstanceForType() {
      return com.ecommerce.grpc.product.ProductResponseChunk.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecommerce.grpc.product.ProductResponseChunk build() {
      com.ecommerce.grpc.product.ProductResponseChunk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecommerce.grpc.product.ProductResponseChunk buildPartial() {
      com.ecommerce.grpc.product.ProductResponseChunk result = new com.ecommerce.grpc.product.ProductResponseChunk(this);
      result.chunk_ = chunk_;
      if (uiActionBuilder_ == null) {
        result.uiAction_ = uiAction_;
      } else {
        result.uiAction_ = uiActionBuilder_.build();
      }
      result.finished_ = finished_;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecommerce.grpc.product.ProductResponseChunk) {
        return mergeFrom((com.ecommerce.grpc.product.ProductResponseChunk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecommerce.grpc.product.ProductResponseChunk other) {
      if (other == com.ecommerce.grpc.product.ProductResponseChunk.getDefaultInstance()) return this;
      if (!other.getChunk().isEmpty()) {
        chunk_ = other.chunk_;
        onChanged();
      }
      if (other.hasUiAction()) {
        mergeUiAction(other.getUiAction());
      }
      if (other.getFinished() != false) {
        setFinished(other.getFinished());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ecommerce.grpc.product.ProductResponseChunk parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ecommerce.grpc.product.ProductResponseChunk) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object chunk_ = "";
    /**
     * <code>string chunk = 1;</code>
     * @return The chunk.
     */
    public java.lang.String getChunk() {
      java.lang.Object ref = chunk_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chunk_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chunk = 1;</code>
     * @return The bytes for chunk.
     */
    public com.google.protobuf.ByteString
        getChunkBytes() {
      java.lang.Object ref = chunk_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chunk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chunk = 1;</code>
     * @param value The chunk to set.
     * @return This builder for chaining.
     */
    public Builder setChunk(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chunk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chunk = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChunk() {
      
      chunk_ = getDefaultInstance().getChunk();
      onChanged();
      return this;
    }
    /**
     * <code>string chunk = 1;</code>
     * @param value The bytes for chunk to set.
     * @return This builder for chaining.
     */
    public Builder setChunkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chunk_ = value;
      onChanged();
      return this;
    }

    private com.ecommerce.grpc.product.ProductUIAction uiAction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.product.ProductUIAction, com.ecommerce.grpc.product.ProductUIAction.Builder, com.ecommerce.grpc.product.ProductUIActionOrBuilder> uiActionBuilder_;
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     * @return Whether the uiAction field is set.
     */
    public boolean hasUiAction() {
      return uiActionBuilder_ != null || uiAction_ != null;
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     * @return The uiAction.
     */
    public com.ecommerce.grpc.product.ProductUIAction getUiAction() {
      if (uiActionBuilder_ == null) {
        return uiAction_ == null ? com.ecommerce.grpc.product.ProductUIAction.getDefaultInstance() : uiAction_;
      } else {
        return uiActionBuilder_.getMessage();
      }
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     */
    public Builder setUiAction(com.ecommerce.grpc.product.ProductUIAction value) {
      if (uiActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        uiAction_ = value;
        onChanged();
      } else {
        uiActionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     */
    public Builder setUiAction(
        com.ecommerce.grpc.product.ProductUIAction.Builder builderForValue) {
      if (uiActionBuilder_ == null) {
        uiAction_ = builderForValue.build();
        onChanged();
      } else {
        uiActionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     */
    public Builder mergeUiAction(com.ecommerce.grpc.product.ProductUIAction value) {
      if (uiActionBuilder_ == null) {
        if (uiAction_ != null) {
          uiAction_ =
            com.ecommerce.grpc.product.ProductUIAction.newBuilder(uiAction_).mergeFrom(value).buildPartial();
        } else {
          uiAction_ = value;
        }
        onChanged();
      } else {
        uiActionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     */
    public Builder clearUiAction() {
      if (uiActionBuilder_ == null) {
        uiAction_ = null;
        onChanged();
      } else {
        uiAction_ = null;
        uiActionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     */
    public com.ecommerce.grpc.product.ProductUIAction.Builder getUiActionBuilder() {
      
      onChanged();
      return getUiActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     */
    public com.ecommerce.grpc.product.ProductUIActionOrBuilder getUiActionOrBuilder() {
      if (uiActionBuilder_ != null) {
        return uiActionBuilder_.getMessageOrBuilder();
      } else {
        return uiAction_ == null ?
            com.ecommerce.grpc.product.ProductUIAction.getDefaultInstance() : uiAction_;
      }
    }
    /**
     * <code>.ecommerce.product.ProductUIAction ui_action = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.product.ProductUIAction, com.ecommerce.grpc.product.ProductUIAction.Builder, com.ecommerce.grpc.product.ProductUIActionOrBuilder> 
        getUiActionFieldBuilder() {
      if (uiActionBuilder_ == null) {
        uiActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecommerce.grpc.product.ProductUIAction, com.ecommerce.grpc.product.ProductUIAction.Builder, com.ecommerce.grpc.product.ProductUIActionOrBuilder>(
                getUiAction(),
                getParentForChildren(),
                isClean());
        uiAction_ = null;
      }
      return uiActionBuilder_;
    }

    private boolean finished_ ;
    /**
     * <code>bool finished = 3;</code>
     * @return The finished.
     */
    @java.lang.Override
    public boolean getFinished() {
      return finished_;
    }
    /**
     * <code>bool finished = 3;</code>
     * @param value The finished to set.
     * @return This builder for chaining.
     */
    public Builder setFinished(boolean value) {
      
      finished_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool finished = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFinished() {
      
      finished_ = false;
      onChanged();
      return this;
    }

    private com.ecommerce.grpc.common.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     * @return The status.
     */
    public com.ecommerce.grpc.common.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.ecommerce.grpc.common.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     */
    public Builder setStatus(com.ecommerce.grpc.common.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     */
    public Builder setStatus(
        com.ecommerce.grpc.common.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     */
    public Builder mergeStatus(com.ecommerce.grpc.common.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.ecommerce.grpc.common.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     */
    public com.ecommerce.grpc.common.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     */
    public com.ecommerce.grpc.common.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.ecommerce.grpc.common.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.ecommerce.common.Status status = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ecommerce.product.ProductResponseChunk)
  }

  // @@protoc_insertion_point(class_scope:ecommerce.product.ProductResponseChunk)
  private static final com.ecommerce.grpc.product.ProductResponseChunk DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecommerce.grpc.product.ProductResponseChunk();
  }

  public static com.ecommerce.grpc.product.ProductResponseChunk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductResponseChunk>
      PARSER = new com.google.protobuf.AbstractParser<ProductResponseChunk>() {
    @java.lang.Override
    public ProductResponseChunk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductResponseChunk(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductResponseChunk> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductResponseChunk> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecommerce.grpc.product.ProductResponseChunk getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

