// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

/**
 * Protobuf type {@code ecommerce.product.ProductBatchResponse}
 */
public final class ProductBatchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ecommerce.product.ProductBatchResponse)
    ProductBatchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductBatchResponse.newBuilder() to construct.
  private ProductBatchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductBatchResponse() {
    products_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductBatchResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductBatchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              products_ = new java.util.ArrayList<com.ecommerce.grpc.product.ProductSummary>();
              mutable_bitField0_ |= 0x00000001;
            }
            products_.add(
                input.readMessage(com.ecommerce.grpc.product.ProductSummary.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.ecommerce.grpc.common.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.ecommerce.grpc.common.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 25: {

            latencyMs_ = input.readDouble();
            break;
          }
          case 34: {
            com.ecommerce.grpc.common.Metadata.Builder subBuilder = null;
            if (metadata_ != null) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(com.ecommerce.grpc.common.Metadata.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        products_ = java.util.Collections.unmodifiableList(products_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductBatchResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductBatchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecommerce.grpc.product.ProductBatchResponse.class, com.ecommerce.grpc.product.ProductBatchResponse.Builder.class);
  }

  public static final int PRODUCTS_FIELD_NUMBER = 1;
  private java.util.List<com.ecommerce.grpc.product.ProductSummary> products_;
  /**
   * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ecommerce.grpc.product.ProductSummary> getProductsList() {
    return products_;
  }
  /**
   * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ecommerce.grpc.product.ProductSummaryOrBuilder> 
      getProductsOrBuilderList() {
    return products_;
  }
  /**
   * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
   */
  @java.lang.Override
  public int getProductsCount() {
    return products_.size();
  }
  /**
   * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.product.ProductSummary getProducts(int index) {
    return products_.get(index);
  }
  /**
   * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.product.ProductSummaryOrBuilder getProductsOrBuilder(
      int index) {
    return products_.get(index);
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private com.ecommerce.grpc.common.Status status_;
  /**
   * <code>.ecommerce.common.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.ecommerce.common.Status status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.Status getStatus() {
    return status_ == null ? com.ecommerce.grpc.common.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.ecommerce.common.Status status = 2;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int LATENCY_MS_FIELD_NUMBER = 3;
  private double latencyMs_;
  /**
   * <code>double latency_ms = 3;</code>
   * @return The latencyMs.
   */
  @java.lang.Override
  public double getLatencyMs() {
    return latencyMs_;
  }

  public static final int METADATA_FIELD_NUMBER = 4;
  private com.ecommerce.grpc.common.Metadata metadata_;
  /**
   * <code>.ecommerce.common.Metadata metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <code>.ecommerce.common.Metadata metadata = 4;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.Metadata getMetadata() {
    return metadata_ == null ? com.ecommerce.grpc.common.Metadata.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.ecommerce.common.Metadata metadata = 4;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.MetadataOrBuilder getMetadataOrBuilder() {
    return getMetadata();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < products_.size(); i++) {
      output.writeMessage(1, products_.get(i));
    }
    if (status_ != null) {
      output.writeMessage(2, getStatus());
    }
    if (java.lang.Double.doubleToRawLongBits(latencyMs_) != 0) {
      output.writeDouble(3, latencyMs_);
    }
    if (metadata_ != null) {
      output.writeMessage(4, getMetadata());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < products_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, products_.get(i));
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStatus());
    }
    if (java.lang.Double.doubleToRawLongBits(latencyMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, latencyMs_);
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMetadata());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecommerce.grpc.product.ProductBatchResponse)) {
      return super.equals(obj);
    }
    com.ecommerce.grpc.product.ProductBatchResponse other = (com.ecommerce.grpc.product.ProductBatchResponse) obj;

    if (!getProductsList()
        .equals(other.getProductsList())) return false;
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getLatencyMs())
        != java.lang.Double.doubleToLongBits(
            other.getLatencyMs())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductsCount() > 0) {
      hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getProductsList().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (37 * hash) + LATENCY_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLatencyMs()));
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.product.ProductBatchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecommerce.grpc.product.ProductBatchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecommerce.product.ProductBatchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecommerce.product.ProductBatchResponse)
      com.ecommerce.grpc.product.ProductBatchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductBatchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductBatchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecommerce.grpc.product.ProductBatchResponse.class, com.ecommerce.grpc.product.ProductBatchResponse.Builder.class);
    }

    // Construct using com.ecommerce.grpc.product.ProductBatchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProductsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        productsBuilder_.clear();
      }
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      latencyMs_ = 0D;

      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecommerce.grpc.product.ProductProto.internal_static_ecommerce_product_ProductBatchResponse_descriptor;
    }

    @java.lang.Override
    public com.ecommerce.grpc.product.ProductBatchResponse getDefaultInstanceForType() {
      return com.ecommerce.grpc.product.ProductBatchResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecommerce.grpc.product.ProductBatchResponse build() {
      com.ecommerce.grpc.product.ProductBatchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecommerce.grpc.product.ProductBatchResponse buildPartial() {
      com.ecommerce.grpc.product.ProductBatchResponse result = new com.ecommerce.grpc.product.ProductBatchResponse(this);
      int from_bitField0_ = bitField0_;
      if (productsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          products_ = java.util.Collections.unmodifiableList(products_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.products_ = products_;
      } else {
        result.products_ = productsBuilder_.build();
      }
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      result.latencyMs_ = latencyMs_;
      if (metadataBuilder_ == null) {
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecommerce.grpc.product.ProductBatchResponse) {
        return mergeFrom((com.ecommerce.grpc.product.ProductBatchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecommerce.grpc.product.ProductBatchResponse other) {
      if (other == com.ecommerce.grpc.product.ProductBatchResponse.getDefaultInstance()) return this;
      if (productsBuilder_ == null) {
        if (!other.products_.isEmpty()) {
          if (products_.isEmpty()) {
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProductsIsMutable();
            products_.addAll(other.products_);
          }
          onChanged();
        }
      } else {
        if (!other.products_.isEmpty()) {
          if (productsBuilder_.isEmpty()) {
            productsBuilder_.dispose();
            productsBuilder_ = null;
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000001);
            productsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProductsFieldBuilder() : null;
          } else {
            productsBuilder_.addAllMessages(other.products_);
          }
        }
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.getLatencyMs() != 0D) {
        setLatencyMs(other.getLatencyMs());
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ecommerce.grpc.product.ProductBatchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ecommerce.grpc.product.ProductBatchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ecommerce.grpc.product.ProductSummary> products_ =
      java.util.Collections.emptyList();
    private void ensureProductsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        products_ = new java.util.ArrayList<com.ecommerce.grpc.product.ProductSummary>(products_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecommerce.grpc.product.ProductSummary, com.ecommerce.grpc.product.ProductSummary.Builder, com.ecommerce.grpc.product.ProductSummaryOrBuilder> productsBuilder_;

    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public java.util.List<com.ecommerce.grpc.product.ProductSummary> getProductsList() {
      if (productsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(products_);
      } else {
        return productsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public int getProductsCount() {
      if (productsBuilder_ == null) {
        return products_.size();
      } else {
        return productsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public com.ecommerce.grpc.product.ProductSummary getProducts(int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);
      } else {
        return productsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder setProducts(
        int index, com.ecommerce.grpc.product.ProductSummary value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.set(index, value);
        onChanged();
      } else {
        productsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder setProducts(
        int index, com.ecommerce.grpc.product.ProductSummary.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.set(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder addProducts(com.ecommerce.grpc.product.ProductSummary value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(value);
        onChanged();
      } else {
        productsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder addProducts(
        int index, com.ecommerce.grpc.product.ProductSummary value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(index, value);
        onChanged();
      } else {
        productsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder addProducts(
        com.ecommerce.grpc.product.ProductSummary.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder addProducts(
        int index, com.ecommerce.grpc.product.ProductSummary.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder addAllProducts(
        java.lang.Iterable<? extends com.ecommerce.grpc.product.ProductSummary> values) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, products_);
        onChanged();
      } else {
        productsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder clearProducts() {
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        productsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public Builder removeProducts(int index) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.remove(index);
        onChanged();
      } else {
        productsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public com.ecommerce.grpc.product.ProductSummary.Builder getProductsBuilder(
        int index) {
      return getProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public com.ecommerce.grpc.product.ProductSummaryOrBuilder getProductsOrBuilder(
        int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);  } else {
        return productsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public java.util.List<? extends com.ecommerce.grpc.product.ProductSummaryOrBuilder> 
         getProductsOrBuilderList() {
      if (productsBuilder_ != null) {
        return productsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(products_);
      }
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public com.ecommerce.grpc.product.ProductSummary.Builder addProductsBuilder() {
      return getProductsFieldBuilder().addBuilder(
          com.ecommerce.grpc.product.ProductSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public com.ecommerce.grpc.product.ProductSummary.Builder addProductsBuilder(
        int index) {
      return getProductsFieldBuilder().addBuilder(
          index, com.ecommerce.grpc.product.ProductSummary.getDefaultInstance());
    }
    /**
     * <code>repeated .ecommerce.product.ProductSummary products = 1;</code>
     */
    public java.util.List<com.ecommerce.grpc.product.ProductSummary.Builder> 
         getProductsBuilderList() {
      return getProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecommerce.grpc.product.ProductSummary, com.ecommerce.grpc.product.ProductSummary.Builder, com.ecommerce.grpc.product.ProductSummaryOrBuilder> 
        getProductsFieldBuilder() {
      if (productsBuilder_ == null) {
        productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ecommerce.grpc.product.ProductSummary, com.ecommerce.grpc.product.ProductSummary.Builder, com.ecommerce.grpc.product.ProductSummaryOrBuilder>(
                products_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        products_ = null;
      }
      return productsBuilder_;
    }

    private com.ecommerce.grpc.common.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     * @return The status.
     */
    public com.ecommerce.grpc.common.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.ecommerce.grpc.common.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     */
    public Builder setStatus(com.ecommerce.grpc.common.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     */
    public Builder setStatus(
        com.ecommerce.grpc.common.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     */
    public Builder mergeStatus(com.ecommerce.grpc.common.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.ecommerce.grpc.common.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     */
    public com.ecommerce.grpc.common.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     */
    public com.ecommerce.grpc.common.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.ecommerce.grpc.common.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.ecommerce.common.Status status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private double latencyMs_ ;
    /**
     * <code>double latency_ms = 3;</code>
     * @return The latencyMs.
     */
    @java.lang.Override
    public double getLatencyMs() {
      return latencyMs_;
    }
    /**
     * <code>double latency_ms = 3;</code>
     * @param value The latencyMs to set.
     * @return This builder for chaining.
     */
    public Builder setLatencyMs(double value) {
      
      latencyMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double latency_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatencyMs() {
      
      latencyMs_ = 0D;
      onChanged();
      return this;
    }

    private com.ecommerce.grpc.common.Metadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Metadata, com.ecommerce.grpc.common.Metadata.Builder, com.ecommerce.grpc.common.MetadataOrBuilder> metadataBuilder_;
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return metadataBuilder_ != null || metadata_ != null;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     * @return The metadata.
     */
    public com.ecommerce.grpc.common.Metadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.ecommerce.grpc.common.Metadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     */
    public Builder setMetadata(com.ecommerce.grpc.common.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     */
    public Builder setMetadata(
        com.ecommerce.grpc.common.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     */
    public Builder mergeMetadata(com.ecommerce.grpc.common.Metadata value) {
      if (metadataBuilder_ == null) {
        if (metadata_ != null) {
          metadata_ =
            com.ecommerce.grpc.common.Metadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     */
    public com.ecommerce.grpc.common.Metadata.Builder getMetadataBuilder() {
      
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     */
    public com.ecommerce.grpc.common.MetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.ecommerce.grpc.common.Metadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Metadata, com.ecommerce.grpc.common.Metadata.Builder, com.ecommerce.grpc.common.MetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecommerce.grpc.common.Metadata, com.ecommerce.grpc.common.Metadata.Builder, com.ecommerce.grpc.common.MetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ecommerce.product.ProductBatchResponse)
  }

  // @@protoc_insertion_point(class_scope:ecommerce.product.ProductBatchResponse)
  private static final com.ecommerce.grpc.product.ProductBatchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecommerce.grpc.product.ProductBatchResponse();
  }

  public static com.ecommerce.grpc.product.ProductBatchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductBatchResponse>
      PARSER = new com.google.protobuf.AbstractParser<ProductBatchResponse>() {
    @java.lang.Override
    public ProductBatchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductBatchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductBatchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductBatchResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecommerce.grpc.product.ProductBatchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

