// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_SearchProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_SearchProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductDetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductDetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_CategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_CategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductBatchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductBatchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductUIAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductUIAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductUIAction_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductUIAction_DataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductResponseChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductResponseChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_BrandInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_BrandInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ImageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ImageInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_CategoryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_CategoryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ecommerce_product_ProductBatchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ecommerce_product_ProductBatchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\021ecommerce.product\032\014comm" +
      "on.proto\"S\n\024SearchProductRequest\022\r\n\005quer" +
      "y\030\001 \001(\t\022,\n\010metadata\030\002 \001(\0132\032.ecommerce.co" +
      "mmon.Metadata\"n\n\024ProductDetailRequest\022\022\n" +
      "\nproduct_id\030\001 \001(\t\022\024\n\014product_name\030\002 \001(\t\022" +
      ",\n\010metadata\030\003 \001(\0132\032.ecommerce.common.Met" +
      "adata\"k\n\017CategoryRequest\022\023\n\013category_id\030" +
      "\001 \001(\t\022\025\n\rcategory_name\030\002 \001(\t\022,\n\010metadata" +
      "\030\003 \001(\0132\032.ecommerce.common.Metadata\"X\n\023Pr" +
      "oductBatchRequest\022\023\n\013product_ids\030\001 \003(\t\022," +
      "\n\010metadata\030\002 \001(\0132\032.ecommerce.common.Meta" +
      "data\"\225\001\n\017ProductUIAction\022\014\n\004type\030\001 \001(\t\022\013" +
      "\n\003url\030\002 \001(\t\022:\n\004data\030\003 \003(\0132,.ecommerce.pr" +
      "oduct.ProductUIAction.DataEntry\032+\n\tDataE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\305\001\n" +
      "\017ProductResponse\022\017\n\007message\030\001 \001(\t\0225\n\tui_" +
      "action\030\002 \001(\0132\".ecommerce.product.Product" +
      "UIAction\022(\n\006status\030\003 \001(\0132\030.ecommerce.com" +
      "mon.Status\022\022\n\nlatency_ms\030\004 \001(\001\022,\n\010metada" +
      "ta\030\005 \001(\0132\032.ecommerce.common.Metadata\"\230\001\n" +
      "\024ProductResponseChunk\022\r\n\005chunk\030\001 \001(\t\0225\n\t" +
      "ui_action\030\002 \001(\0132\".ecommerce.product.Prod" +
      "uctUIAction\022\020\n\010finished\030\003 \001(\010\022(\n\006status\030" +
      "\004 \001(\0132\030.ecommerce.common.Status\"\333\002\n\016Prod" +
      "uctSummary\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\031\n\021" +
      "short_description\030\003 \001(\t\022\r\n\005price\030\004 \001(\001\022\026" +
      "\n\016original_price\030\005 \001(\001\022\026\n\016rating_average" +
      "\030\006 \001(\001\022\024\n\014review_count\030\007 \001(\005\022\030\n\020inventor" +
      "y_status\030\010 \001(\t\022\025\n\rquantity_sold\030\t \001(\005\022+\n" +
      "\005brand\030\n \001(\0132\034.ecommerce.product.BrandIn" +
      "fo\022,\n\006images\030\013 \003(\0132\034.ecommerce.product.I" +
      "mageInfo\0223\n\ncategories\030\014 \003(\0132\037.ecommerce" +
      ".product.CategoryInfo\"N\n\tBrandInfo\022\n\n\002id" +
      "\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004slug\030\003 \001(\t\022\031\n\021co" +
      "untry_of_origin\030\004 \001(\t\"6\n\tImageInfo\022\n\n\002id" +
      "\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\020\n\010position\030\003 \001(\005\"W\n" +
      "\014CategoryInfo\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022" +
      "\013\n\003url\030\003 \001(\t\022\021\n\tparent_id\030\004 \001(\t\022\r\n\005level" +
      "\030\005 \001(\005\"\267\001\n\024ProductBatchResponse\0223\n\010produ" +
      "cts\030\001 \003(\0132!.ecommerce.product.ProductSum" +
      "mary\022(\n\006status\030\002 \001(\0132\030.ecommerce.common." +
      "Status\022\022\n\nlatency_ms\030\003 \001(\001\022,\n\010metadata\030\004" +
      " \001(\0132\032.ecommerce.common.Metadata2\366\003\n\016Pro" +
      "ductService\022\\\n\rSearchProduct\022\'.ecommerce" +
      ".product.SearchProductRequest\032\".ecommerc" +
      "e.product.ProductResponse\022_\n\020GetProductD" +
      "etail\022\'.ecommerce.product.ProductDetailR" +
      "equest\032\".ecommerce.product.ProductRespon" +
      "se\022U\n\013GetCategory\022\".ecommerce.product.Ca" +
      "tegoryRequest\032\".ecommerce.product.Produc" +
      "tResponse\022c\n\020GetProductsBatch\022&.ecommerc" +
      "e.product.ProductBatchRequest\032\'.ecommerc" +
      "e.product.ProductBatchResponse\022i\n\023Search" +
      "ProductStream\022\'.ecommerce.product.Search" +
      "ProductRequest\032\'.ecommerce.product.Produ" +
      "ctResponseChunk0\001B,\n\032com.ecommerce.grpc." +
      "productB\014ProductProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ecommerce.grpc.common.CommonProto.getDescriptor(),
        });
    internal_static_ecommerce_product_SearchProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ecommerce_product_SearchProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_SearchProductRequest_descriptor,
        new java.lang.String[] { "Query", "Metadata", });
    internal_static_ecommerce_product_ProductDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ecommerce_product_ProductDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductDetailRequest_descriptor,
        new java.lang.String[] { "ProductId", "ProductName", "Metadata", });
    internal_static_ecommerce_product_CategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ecommerce_product_CategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_CategoryRequest_descriptor,
        new java.lang.String[] { "CategoryId", "CategoryName", "Metadata", });
    internal_static_ecommerce_product_ProductBatchRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ecommerce_product_ProductBatchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductBatchRequest_descriptor,
        new java.lang.String[] { "ProductIds", "Metadata", });
    internal_static_ecommerce_product_ProductUIAction_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ecommerce_product_ProductUIAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductUIAction_descriptor,
        new java.lang.String[] { "Type", "Url", "Data", });
    internal_static_ecommerce_product_ProductUIAction_DataEntry_descriptor =
      internal_static_ecommerce_product_ProductUIAction_descriptor.getNestedTypes().get(0);
    internal_static_ecommerce_product_ProductUIAction_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductUIAction_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ecommerce_product_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ecommerce_product_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductResponse_descriptor,
        new java.lang.String[] { "Message", "UiAction", "Status", "LatencyMs", "Metadata", });
    internal_static_ecommerce_product_ProductResponseChunk_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ecommerce_product_ProductResponseChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductResponseChunk_descriptor,
        new java.lang.String[] { "Chunk", "UiAction", "Finished", "Status", });
    internal_static_ecommerce_product_ProductSummary_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ecommerce_product_ProductSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductSummary_descriptor,
        new java.lang.String[] { "Id", "Name", "ShortDescription", "Price", "OriginalPrice", "RatingAverage", "ReviewCount", "InventoryStatus", "QuantitySold", "Brand", "Images", "Categories", });
    internal_static_ecommerce_product_BrandInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ecommerce_product_BrandInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_BrandInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Slug", "CountryOfOrigin", });
    internal_static_ecommerce_product_ImageInfo_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ecommerce_product_ImageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ImageInfo_descriptor,
        new java.lang.String[] { "Id", "Url", "Position", });
    internal_static_ecommerce_product_CategoryInfo_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ecommerce_product_CategoryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_CategoryInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Url", "ParentId", "Level", });
    internal_static_ecommerce_product_ProductBatchResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ecommerce_product_ProductBatchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ecommerce_product_ProductBatchResponse_descriptor,
        new java.lang.String[] { "Products", "Status", "LatencyMs", "Metadata", });
    com.ecommerce.grpc.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
