// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

public interface ProductBatchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.product.ProductBatchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string product_ids = 1;</code>
   * @return A list containing the productIds.
   */
  java.util.List<java.lang.String>
      getProductIdsList();
  /**
   * <code>repeated string product_ids = 1;</code>
   * @return The count of productIds.
   */
  int getProductIdsCount();
  /**
   * <code>repeated string product_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  java.lang.String getProductIds(int index);
  /**
   * <code>repeated string product_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the productIds at the given index.
   */
  com.google.protobuf.ByteString
      getProductIdsBytes(int index);

  /**
   * <code>.ecommerce.common.Metadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.ecommerce.common.Metadata metadata = 2;</code>
   * @return The metadata.
   */
  com.ecommerce.grpc.common.Metadata getMetadata();
  /**
   * <code>.ecommerce.common.Metadata metadata = 2;</code>
   */
  com.ecommerce.grpc.common.MetadataOrBuilder getMetadataOrBuilder();
}
