// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ecommerce.grpc.product;

public interface ProductSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.product.ProductSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string short_description = 3;</code>
   * @return The shortDescription.
   */
  java.lang.String getShortDescription();
  /**
   * <code>string short_description = 3;</code>
   * @return The bytes for shortDescription.
   */
  com.google.protobuf.ByteString
      getShortDescriptionBytes();

  /**
   * <code>double price = 4;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>double original_price = 5;</code>
   * @return The originalPrice.
   */
  double getOriginalPrice();

  /**
   * <code>double rating_average = 6;</code>
   * @return The ratingAverage.
   */
  double getRatingAverage();

  /**
   * <code>int32 review_count = 7;</code>
   * @return The reviewCount.
   */
  int getReviewCount();

  /**
   * <code>string inventory_status = 8;</code>
   * @return The inventoryStatus.
   */
  java.lang.String getInventoryStatus();
  /**
   * <code>string inventory_status = 8;</code>
   * @return The bytes for inventoryStatus.
   */
  com.google.protobuf.ByteString
      getInventoryStatusBytes();

  /**
   * <code>int32 quantity_sold = 9;</code>
   * @return The quantitySold.
   */
  int getQuantitySold();

  /**
   * <code>.ecommerce.product.BrandInfo brand = 10;</code>
   * @return Whether the brand field is set.
   */
  boolean hasBrand();
  /**
   * <code>.ecommerce.product.BrandInfo brand = 10;</code>
   * @return The brand.
   */
  com.ecommerce.grpc.product.BrandInfo getBrand();
  /**
   * <code>.ecommerce.product.BrandInfo brand = 10;</code>
   */
  com.ecommerce.grpc.product.BrandInfoOrBuilder getBrandOrBuilder();

  /**
   * <code>repeated .ecommerce.product.ImageInfo images = 11;</code>
   */
  java.util.List<com.ecommerce.grpc.product.ImageInfo> 
      getImagesList();
  /**
   * <code>repeated .ecommerce.product.ImageInfo images = 11;</code>
   */
  com.ecommerce.grpc.product.ImageInfo getImages(int index);
  /**
   * <code>repeated .ecommerce.product.ImageInfo images = 11;</code>
   */
  int getImagesCount();
  /**
   * <code>repeated .ecommerce.product.ImageInfo images = 11;</code>
   */
  java.util.List<? extends com.ecommerce.grpc.product.ImageInfoOrBuilder> 
      getImagesOrBuilderList();
  /**
   * <code>repeated .ecommerce.product.ImageInfo images = 11;</code>
   */
  com.ecommerce.grpc.product.ImageInfoOrBuilder getImagesOrBuilder(
      int index);

  /**
   * <code>repeated .ecommerce.product.CategoryInfo categories = 12;</code>
   */
  java.util.List<com.ecommerce.grpc.product.CategoryInfo> 
      getCategoriesList();
  /**
   * <code>repeated .ecommerce.product.CategoryInfo categories = 12;</code>
   */
  com.ecommerce.grpc.product.CategoryInfo getCategories(int index);
  /**
   * <code>repeated .ecommerce.product.CategoryInfo categories = 12;</code>
   */
  int getCategoriesCount();
  /**
   * <code>repeated .ecommerce.product.CategoryInfo categories = 12;</code>
   */
  java.util.List<? extends com.ecommerce.grpc.product.CategoryInfoOrBuilder> 
      getCategoriesOrBuilderList();
  /**
   * <code>repeated .ecommerce.product.CategoryInfo categories = 12;</code>
   */
  com.ecommerce.grpc.product.CategoryInfoOrBuilder getCategoriesOrBuilder(
      int index);
}
