services:
  redis-notification:
    image: redis:7.2-alpine
    container_name: ecommerce-redis-notification
    ports:
      - "6383:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_notification_data:/data
    networks:
      - ecommerce-shared-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_notification_data:

networks:
  ecommerce-shared-network:
    external: true
