services:
  mysql:
    image: mysql:8.0
    container_name: product-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: ecommerce_product
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-shared-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootPassword" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  ecommerce-shared-network:
    external: true