// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.ecommerce.grpc.inventory;

/**
 * Protobuf type {@code ecommerce.inventory.CheckInventoryBatchResponse}
 */
public final class CheckInventoryBatchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ecommerce.inventory.CheckInventoryBatchResponse)
    CheckInventoryBatchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckInventoryBatchResponse.newBuilder() to construct.
  private CheckInventoryBatchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckInventoryBatchResponse() {
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckInventoryBatchResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckInventoryBatchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<com.ecommerce.grpc.inventory.InventoryStatus>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(com.ecommerce.grpc.inventory.InventoryStatus.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.ecommerce.grpc.common.Status.Builder subBuilder = null;
            if (resultStatus_ != null) {
              subBuilder = resultStatus_.toBuilder();
            }
            resultStatus_ = input.readMessage(com.ecommerce.grpc.common.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resultStatus_);
              resultStatus_ = subBuilder.buildPartial();
            }

            break;
          }
          case 25: {

            latencyMs_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecommerce.grpc.inventory.CheckInventoryBatchResponse.class, com.ecommerce.grpc.inventory.CheckInventoryBatchResponse.Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<com.ecommerce.grpc.inventory.InventoryStatus> items_;
  /**
   * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ecommerce.grpc.inventory.InventoryStatus> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ecommerce.grpc.inventory.InventoryStatusOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.inventory.InventoryStatus getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.inventory.InventoryStatusOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int RESULT_STATUS_FIELD_NUMBER = 2;
  private com.ecommerce.grpc.common.Status resultStatus_;
  /**
   * <code>.ecommerce.common.Status result_status = 2;</code>
   * @return Whether the resultStatus field is set.
   */
  @java.lang.Override
  public boolean hasResultStatus() {
    return resultStatus_ != null;
  }
  /**
   * <code>.ecommerce.common.Status result_status = 2;</code>
   * @return The resultStatus.
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.Status getResultStatus() {
    return resultStatus_ == null ? com.ecommerce.grpc.common.Status.getDefaultInstance() : resultStatus_;
  }
  /**
   * <code>.ecommerce.common.Status result_status = 2;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.StatusOrBuilder getResultStatusOrBuilder() {
    return getResultStatus();
  }

  public static final int LATENCY_MS_FIELD_NUMBER = 3;
  private double latencyMs_;
  /**
   * <code>double latency_ms = 3;</code>
   * @return The latencyMs.
   */
  @java.lang.Override
  public double getLatencyMs() {
    return latencyMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (resultStatus_ != null) {
      output.writeMessage(2, getResultStatus());
    }
    if (java.lang.Double.doubleToRawLongBits(latencyMs_) != 0) {
      output.writeDouble(3, latencyMs_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    if (resultStatus_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResultStatus());
    }
    if (java.lang.Double.doubleToRawLongBits(latencyMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, latencyMs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecommerce.grpc.inventory.CheckInventoryBatchResponse)) {
      return super.equals(obj);
    }
    com.ecommerce.grpc.inventory.CheckInventoryBatchResponse other = (com.ecommerce.grpc.inventory.CheckInventoryBatchResponse) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (hasResultStatus() != other.hasResultStatus()) return false;
    if (hasResultStatus()) {
      if (!getResultStatus()
          .equals(other.getResultStatus())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getLatencyMs())
        != java.lang.Double.doubleToLongBits(
            other.getLatencyMs())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    if (hasResultStatus()) {
      hash = (37 * hash) + RESULT_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getResultStatus().hashCode();
    }
    hash = (37 * hash) + LATENCY_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLatencyMs()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecommerce.grpc.inventory.CheckInventoryBatchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecommerce.inventory.CheckInventoryBatchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecommerce.inventory.CheckInventoryBatchResponse)
      com.ecommerce.grpc.inventory.CheckInventoryBatchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecommerce.grpc.inventory.CheckInventoryBatchResponse.class, com.ecommerce.grpc.inventory.CheckInventoryBatchResponse.Builder.class);
    }

    // Construct using com.ecommerce.grpc.inventory.CheckInventoryBatchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      if (resultStatusBuilder_ == null) {
        resultStatus_ = null;
      } else {
        resultStatus_ = null;
        resultStatusBuilder_ = null;
      }
      latencyMs_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchResponse_descriptor;
    }

    @java.lang.Override
    public com.ecommerce.grpc.inventory.CheckInventoryBatchResponse getDefaultInstanceForType() {
      return com.ecommerce.grpc.inventory.CheckInventoryBatchResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecommerce.grpc.inventory.CheckInventoryBatchResponse build() {
      com.ecommerce.grpc.inventory.CheckInventoryBatchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecommerce.grpc.inventory.CheckInventoryBatchResponse buildPartial() {
      com.ecommerce.grpc.inventory.CheckInventoryBatchResponse result = new com.ecommerce.grpc.inventory.CheckInventoryBatchResponse(this);
      int from_bitField0_ = bitField0_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      if (resultStatusBuilder_ == null) {
        result.resultStatus_ = resultStatus_;
      } else {
        result.resultStatus_ = resultStatusBuilder_.build();
      }
      result.latencyMs_ = latencyMs_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecommerce.grpc.inventory.CheckInventoryBatchResponse) {
        return mergeFrom((com.ecommerce.grpc.inventory.CheckInventoryBatchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecommerce.grpc.inventory.CheckInventoryBatchResponse other) {
      if (other == com.ecommerce.grpc.inventory.CheckInventoryBatchResponse.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.hasResultStatus()) {
        mergeResultStatus(other.getResultStatus());
      }
      if (other.getLatencyMs() != 0D) {
        setLatencyMs(other.getLatencyMs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ecommerce.grpc.inventory.CheckInventoryBatchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ecommerce.grpc.inventory.CheckInventoryBatchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ecommerce.grpc.inventory.InventoryStatus> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.ecommerce.grpc.inventory.InventoryStatus>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecommerce.grpc.inventory.InventoryStatus, com.ecommerce.grpc.inventory.InventoryStatus.Builder, com.ecommerce.grpc.inventory.InventoryStatusOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public java.util.List<com.ecommerce.grpc.inventory.InventoryStatus> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryStatus getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder setItems(
        int index, com.ecommerce.grpc.inventory.InventoryStatus value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder setItems(
        int index, com.ecommerce.grpc.inventory.InventoryStatus.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder addItems(com.ecommerce.grpc.inventory.InventoryStatus value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder addItems(
        int index, com.ecommerce.grpc.inventory.InventoryStatus value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder addItems(
        com.ecommerce.grpc.inventory.InventoryStatus.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder addItems(
        int index, com.ecommerce.grpc.inventory.InventoryStatus.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.ecommerce.grpc.inventory.InventoryStatus> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryStatus.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryStatusOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public java.util.List<? extends com.ecommerce.grpc.inventory.InventoryStatusOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryStatus.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.ecommerce.grpc.inventory.InventoryStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryStatus.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.ecommerce.grpc.inventory.InventoryStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryStatus items = 1;</code>
     */
    public java.util.List<com.ecommerce.grpc.inventory.InventoryStatus.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecommerce.grpc.inventory.InventoryStatus, com.ecommerce.grpc.inventory.InventoryStatus.Builder, com.ecommerce.grpc.inventory.InventoryStatusOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ecommerce.grpc.inventory.InventoryStatus, com.ecommerce.grpc.inventory.InventoryStatus.Builder, com.ecommerce.grpc.inventory.InventoryStatusOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private com.ecommerce.grpc.common.Status resultStatus_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder> resultStatusBuilder_;
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     * @return Whether the resultStatus field is set.
     */
    public boolean hasResultStatus() {
      return resultStatusBuilder_ != null || resultStatus_ != null;
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     * @return The resultStatus.
     */
    public com.ecommerce.grpc.common.Status getResultStatus() {
      if (resultStatusBuilder_ == null) {
        return resultStatus_ == null ? com.ecommerce.grpc.common.Status.getDefaultInstance() : resultStatus_;
      } else {
        return resultStatusBuilder_.getMessage();
      }
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     */
    public Builder setResultStatus(com.ecommerce.grpc.common.Status value) {
      if (resultStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resultStatus_ = value;
        onChanged();
      } else {
        resultStatusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     */
    public Builder setResultStatus(
        com.ecommerce.grpc.common.Status.Builder builderForValue) {
      if (resultStatusBuilder_ == null) {
        resultStatus_ = builderForValue.build();
        onChanged();
      } else {
        resultStatusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     */
    public Builder mergeResultStatus(com.ecommerce.grpc.common.Status value) {
      if (resultStatusBuilder_ == null) {
        if (resultStatus_ != null) {
          resultStatus_ =
            com.ecommerce.grpc.common.Status.newBuilder(resultStatus_).mergeFrom(value).buildPartial();
        } else {
          resultStatus_ = value;
        }
        onChanged();
      } else {
        resultStatusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     */
    public Builder clearResultStatus() {
      if (resultStatusBuilder_ == null) {
        resultStatus_ = null;
        onChanged();
      } else {
        resultStatus_ = null;
        resultStatusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     */
    public com.ecommerce.grpc.common.Status.Builder getResultStatusBuilder() {
      
      onChanged();
      return getResultStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     */
    public com.ecommerce.grpc.common.StatusOrBuilder getResultStatusOrBuilder() {
      if (resultStatusBuilder_ != null) {
        return resultStatusBuilder_.getMessageOrBuilder();
      } else {
        return resultStatus_ == null ?
            com.ecommerce.grpc.common.Status.getDefaultInstance() : resultStatus_;
      }
    }
    /**
     * <code>.ecommerce.common.Status result_status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder> 
        getResultStatusFieldBuilder() {
      if (resultStatusBuilder_ == null) {
        resultStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecommerce.grpc.common.Status, com.ecommerce.grpc.common.Status.Builder, com.ecommerce.grpc.common.StatusOrBuilder>(
                getResultStatus(),
                getParentForChildren(),
                isClean());
        resultStatus_ = null;
      }
      return resultStatusBuilder_;
    }

    private double latencyMs_ ;
    /**
     * <code>double latency_ms = 3;</code>
     * @return The latencyMs.
     */
    @java.lang.Override
    public double getLatencyMs() {
      return latencyMs_;
    }
    /**
     * <code>double latency_ms = 3;</code>
     * @param value The latencyMs to set.
     * @return This builder for chaining.
     */
    public Builder setLatencyMs(double value) {
      
      latencyMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double latency_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatencyMs() {
      
      latencyMs_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ecommerce.inventory.CheckInventoryBatchResponse)
  }

  // @@protoc_insertion_point(class_scope:ecommerce.inventory.CheckInventoryBatchResponse)
  private static final com.ecommerce.grpc.inventory.CheckInventoryBatchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecommerce.grpc.inventory.CheckInventoryBatchResponse();
  }

  public static com.ecommerce.grpc.inventory.CheckInventoryBatchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckInventoryBatchResponse>
      PARSER = new com.google.protobuf.AbstractParser<CheckInventoryBatchResponse>() {
    @java.lang.Override
    public CheckInventoryBatchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckInventoryBatchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckInventoryBatchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckInventoryBatchResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecommerce.grpc.inventory.CheckInventoryBatchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

