// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.ecommerce.grpc.inventory;

public interface CheckInventoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.inventory.CheckInventoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>bool available = 2;</code>
   * @return The available.
   */
  boolean getAvailable();

  /**
   * <code>int32 available_quantity = 3;</code>
   * @return The availableQuantity.
   */
  int getAvailableQuantity();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>.ecommerce.common.Status result_status = 5;</code>
   * @return Whether the resultStatus field is set.
   */
  boolean hasResultStatus();
  /**
   * <code>.ecommerce.common.Status result_status = 5;</code>
   * @return The resultStatus.
   */
  com.ecommerce.grpc.common.Status getResultStatus();
  /**
   * <code>.ecommerce.common.Status result_status = 5;</code>
   */
  com.ecommerce.grpc.common.StatusOrBuilder getResultStatusOrBuilder();

  /**
   * <code>double latency_ms = 6;</code>
   * @return The latencyMs.
   */
  double getLatencyMs();
}
