// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.ecommerce.grpc.inventory;

/**
 * Protobuf type {@code ecommerce.inventory.CheckInventoryBatchRequest}
 */
public final class CheckInventoryBatchRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ecommerce.inventory.CheckInventoryBatchRequest)
    CheckInventoryBatchRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckInventoryBatchRequest.newBuilder() to construct.
  private CheckInventoryBatchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckInventoryBatchRequest() {
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckInventoryBatchRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckInventoryBatchRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              items_ = new java.util.ArrayList<com.ecommerce.grpc.inventory.InventoryItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(com.ecommerce.grpc.inventory.InventoryItem.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.ecommerce.grpc.common.Metadata.Builder subBuilder = null;
            if (metadata_ != null) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(com.ecommerce.grpc.common.Metadata.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ecommerce.grpc.inventory.CheckInventoryBatchRequest.class, com.ecommerce.grpc.inventory.CheckInventoryBatchRequest.Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<com.ecommerce.grpc.inventory.InventoryItem> items_;
  /**
   * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ecommerce.grpc.inventory.InventoryItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ecommerce.grpc.inventory.InventoryItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.inventory.InventoryItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.inventory.InventoryItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int METADATA_FIELD_NUMBER = 2;
  private com.ecommerce.grpc.common.Metadata metadata_;
  /**
   * <code>.ecommerce.common.Metadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <code>.ecommerce.common.Metadata metadata = 2;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.Metadata getMetadata() {
    return metadata_ == null ? com.ecommerce.grpc.common.Metadata.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.ecommerce.common.Metadata metadata = 2;</code>
   */
  @java.lang.Override
  public com.ecommerce.grpc.common.MetadataOrBuilder getMetadataOrBuilder() {
    return getMetadata();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (metadata_ != null) {
      output.writeMessage(2, getMetadata());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetadata());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ecommerce.grpc.inventory.CheckInventoryBatchRequest)) {
      return super.equals(obj);
    }
    com.ecommerce.grpc.inventory.CheckInventoryBatchRequest other = (com.ecommerce.grpc.inventory.CheckInventoryBatchRequest) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ecommerce.grpc.inventory.CheckInventoryBatchRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ecommerce.inventory.CheckInventoryBatchRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ecommerce.inventory.CheckInventoryBatchRequest)
      com.ecommerce.grpc.inventory.CheckInventoryBatchRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ecommerce.grpc.inventory.CheckInventoryBatchRequest.class, com.ecommerce.grpc.inventory.CheckInventoryBatchRequest.Builder.class);
    }

    // Construct using com.ecommerce.grpc.inventory.CheckInventoryBatchRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ecommerce.grpc.inventory.InventoryProto.internal_static_ecommerce_inventory_CheckInventoryBatchRequest_descriptor;
    }

    @java.lang.Override
    public com.ecommerce.grpc.inventory.CheckInventoryBatchRequest getDefaultInstanceForType() {
      return com.ecommerce.grpc.inventory.CheckInventoryBatchRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ecommerce.grpc.inventory.CheckInventoryBatchRequest build() {
      com.ecommerce.grpc.inventory.CheckInventoryBatchRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ecommerce.grpc.inventory.CheckInventoryBatchRequest buildPartial() {
      com.ecommerce.grpc.inventory.CheckInventoryBatchRequest result = new com.ecommerce.grpc.inventory.CheckInventoryBatchRequest(this);
      int from_bitField0_ = bitField0_;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      if (metadataBuilder_ == null) {
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ecommerce.grpc.inventory.CheckInventoryBatchRequest) {
        return mergeFrom((com.ecommerce.grpc.inventory.CheckInventoryBatchRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ecommerce.grpc.inventory.CheckInventoryBatchRequest other) {
      if (other == com.ecommerce.grpc.inventory.CheckInventoryBatchRequest.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ecommerce.grpc.inventory.CheckInventoryBatchRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ecommerce.grpc.inventory.CheckInventoryBatchRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ecommerce.grpc.inventory.InventoryItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.ecommerce.grpc.inventory.InventoryItem>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecommerce.grpc.inventory.InventoryItem, com.ecommerce.grpc.inventory.InventoryItem.Builder, com.ecommerce.grpc.inventory.InventoryItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public java.util.List<com.ecommerce.grpc.inventory.InventoryItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.ecommerce.grpc.inventory.InventoryItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.ecommerce.grpc.inventory.InventoryItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder addItems(com.ecommerce.grpc.inventory.InventoryItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.ecommerce.grpc.inventory.InventoryItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder addItems(
        com.ecommerce.grpc.inventory.InventoryItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.ecommerce.grpc.inventory.InventoryItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.ecommerce.grpc.inventory.InventoryItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public java.util.List<? extends com.ecommerce.grpc.inventory.InventoryItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.ecommerce.grpc.inventory.InventoryItem.getDefaultInstance());
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public com.ecommerce.grpc.inventory.InventoryItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.ecommerce.grpc.inventory.InventoryItem.getDefaultInstance());
    }
    /**
     * <code>repeated .ecommerce.inventory.InventoryItem items = 1;</code>
     */
    public java.util.List<com.ecommerce.grpc.inventory.InventoryItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ecommerce.grpc.inventory.InventoryItem, com.ecommerce.grpc.inventory.InventoryItem.Builder, com.ecommerce.grpc.inventory.InventoryItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ecommerce.grpc.inventory.InventoryItem, com.ecommerce.grpc.inventory.InventoryItem.Builder, com.ecommerce.grpc.inventory.InventoryItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private com.ecommerce.grpc.common.Metadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Metadata, com.ecommerce.grpc.common.Metadata.Builder, com.ecommerce.grpc.common.MetadataOrBuilder> metadataBuilder_;
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return metadataBuilder_ != null || metadata_ != null;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     * @return The metadata.
     */
    public com.ecommerce.grpc.common.Metadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.ecommerce.grpc.common.Metadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     */
    public Builder setMetadata(com.ecommerce.grpc.common.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     */
    public Builder setMetadata(
        com.ecommerce.grpc.common.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     */
    public Builder mergeMetadata(com.ecommerce.grpc.common.Metadata value) {
      if (metadataBuilder_ == null) {
        if (metadata_ != null) {
          metadata_ =
            com.ecommerce.grpc.common.Metadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     */
    public com.ecommerce.grpc.common.Metadata.Builder getMetadataBuilder() {
      
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     */
    public com.ecommerce.grpc.common.MetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.ecommerce.grpc.common.Metadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.ecommerce.common.Metadata metadata = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ecommerce.grpc.common.Metadata, com.ecommerce.grpc.common.Metadata.Builder, com.ecommerce.grpc.common.MetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ecommerce.grpc.common.Metadata, com.ecommerce.grpc.common.Metadata.Builder, com.ecommerce.grpc.common.MetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ecommerce.inventory.CheckInventoryBatchRequest)
  }

  // @@protoc_insertion_point(class_scope:ecommerce.inventory.CheckInventoryBatchRequest)
  private static final com.ecommerce.grpc.inventory.CheckInventoryBatchRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ecommerce.grpc.inventory.CheckInventoryBatchRequest();
  }

  public static com.ecommerce.grpc.inventory.CheckInventoryBatchRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckInventoryBatchRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckInventoryBatchRequest>() {
    @java.lang.Override
    public CheckInventoryBatchRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckInventoryBatchRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckInventoryBatchRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckInventoryBatchRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ecommerce.grpc.inventory.CheckInventoryBatchRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

