// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package com.ecommerce.grpc.inventory;

public interface InventoryItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ecommerce.inventory.InventoryItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();
}
